name = "Yacs"
author = "AlexDevs"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b710cbf3ba989e04b264c2b8729ac49a6b8225804c3075a49f8c9bf7e7c0dc37"

[versions]
fabric = "0.16.8"
minecraft = "1.20.1"
