name = "Yacs"
author = "AlexDevs"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4c4c89939c3c9c5f5c65d1e64f3bcf4805c22b684eccc7a299dd86181127c36"

[versions]
fabric = "0.16.8"
minecraft = "1.20.1"
